export const GET_ORDER_REQUEST: 'GET_ORDER_REQUEST' = 'GET_ORDER_REQUEST';
export const GET_ORDER_SUCCESS: 'GET_ORDER_SUCCESS' = 'GET_ORDER_SUCCESS';
export const GET_ORDER_FAILED: 'GET_ORDER_FAILED' = 'GET_ORDER_FAILED';
export const WATCH_ORDERS_PUBLIC_OPEN: 'WATCH_ORDERS_PUBLIC_OPEN' = 'WATCH_ORDERS_PUBLIC_OPEN';
export const WATCH_ORDERS_PUBLIC_SUCCESS: 'WATCH_ORDERS_PUBLIC_SUCCESS' = 'WATCH_ORDERS_PUBLIC_SUCCESS';
export const WATCH_ORDERS_PUBLIC_DATA: 'WATCH_ORDERS_PUBLIC_DATA' = 'WATCH_ORDERS_PUBLIC_DATA';
export const CURRENT_ORDER: 'CURRENT_ORDER' = 'CURRENT_ORDER';